# Generated by Django 2.2 on 2020-01-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_munites',
            new_name='time_miuntie',
        ),
    ]
