# Generated by Django 2.2 on 2020-01-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200108_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/recipes/%Y/%m/%d/'),
        ),
    ]
